### ISSUE TITLE
How to determine which variables should share memory in an "shared_optimizer"

### ISSUE THREAD

**Issue by huguyuehuhu** [MorvanZhou/pytorch-A3C#2]
Hi, can you give me some advice that **How to determine which variables should share memory in an "shared_optimizer"**;
1. I find that you share memory of some variable 
`state['exp_avg'].share_memory_()
 state['exp_avg_sq'].share_memory_()
`
 in your [shared_adam.py](https://github.com/MorvanZhou/pytorch-A3C/blob/master/shared_adam.py); but [others ](https://github.com/jingweiz/pytorch-rl/blob/20b3b738ca400b1916197f27a91367878b09803c/optims/sharedAdam.py)also shared step;
`state['step'].share_memory_()`
2. also in shared_RMSprop , [here](https://github.com/jingweiz/pytorch-rl/blob/20b3b738ca400b1916197f27a91367878b09803c/optims/sharedRMSprop.py) is share different with [here](https://github.com/wuhuikai/a3c-deepmind-pytorch/blob/master/optimizer.py);

Thank you advance!

**Comment by huguyuehuhu** [comment]
Finally, I got it! Hi, MorVan, your code have not share state['step'], which caused a wrong bias_correction. Refer to  [here](https://github.com/ikostrikov/pytorch-a3c/issues/12), it should be fixed to like [this](https://github.com/ikostrikov/pytorch-a3c/commit/5d9b07d80740e26f78cb283f74b5b802906a9d83) .

**Comment by huguyuehuhu** [comment]
Finally, I got it! Hi, MorVan, your code have not shared `state['step']`, which will cause a wrong `bias_correction`. Refer to [here](https://github.com/ikostrikov/pytorch-a3c/issues/12), it should be fixed to like [this](https://github.com/ikostrikov/pytorch-a3c/commit/5d9b07d80740e26f78cb283f74b5b802906a9d83) .

**Comment by huguyuehuhu** [comment]
Finally, I got it! Hi, @MorvanZhou , your code have not shared` state['step']`, which will cause a wrong `bias_correction`. Refer to [here](https://github.com/ikostrikov/pytorch-a3c/issues/12), it should be fixed to like [this](https://github.com/ikostrikov/pytorch-a3c/commit/5d9b07d80740e26f78cb283f74b5b802906a9d83) .

**Comment by MorvanZhou** [comment]
Thanks, that is indeed a problem for adam but not for rmsprop. The reason I choose rmsprop is that I don't need to add 'step()'
