### ISSUE TITLE
多进程、多线程问题

### ISSUE THREAD

**Issue by DreamerSurpass** [MorvanZhou/pytorch-A3C#28]
近期在编写pytorch多线程、多进程算法训练。

想问一下如果是使用thread多线程训练的话，还需要进行share memory的操作吗？

**Comment by MorvanZhou** [comment]
以我的理解，threading 的话，不需要在进程间 share 的。线程间的 share 更简单点。但是 pytorch 要怎么设置，我还没有尝试过

**Comment by DreamerSurpass** [comment]
好的好的，感谢迅速回复，我试试。
之前看到过一些RL多进程的训练，以我的理解是多个进程分别在满足条件后更新全局网络，然后局部网络再加载参数。
我有点疑惑这样会不会让训练不稳定？还有使用多进程/线程的更新，能否使用On Policy如PPO这样的算法呢？
