### ISSUE TITLE
无法拓展到其他env

### ISSUE THREAD

**Issue by wangyouzhuo** [MorvanZhou/pytorch-A3C#9]
周老师 我遇到一个很奇怪的问题：我把pytorch的a3c中所有关于s维度的变量都补0，也就是把env的s从原来的4拓宽到2048以后，代码中的“forward函数”不报错，但是会卡在这个函数里面不动。我仔细检查过，网络没有任何维度匹配上的问题，但是自己现在反复搞不定这个问题。你有什么思路吗？

**Comment by Georay7** [comment]
你试试把网络节点数改到1024还会出现这种情况的

**Comment by wangyouzhuo** [comment]
> 你试试把网络节点数改到1024还会出现这种情况的
有解吗 ？我试了，基本上只要节点数超过200就无法forward。而且我找到的其他pytorch-a3c的demo中也存在这个问题，不仅是Linear，conv也会这样。

**Comment by Georay7** [comment]
换到win下运行就OK

**Comment by wangyouzhuo** [comment]
> 换到win下运行就OK
这都可以

**Comment by KaiKangSDU** [comment]
周老师你好，我想请问一下这个loss函数的定义可以在哪些参考资料上找到呀？有更深一步的解释吗？谢谢

**Comment by Georay7** [comment]
> > 换到win下运行就OK
> > 这都可以
查一下共享内存 /dev/shm 的大小，默认是64M，应该是这里出了问题，可以改大一点尝试下

**Comment by liuxiaotong15** [comment]
我的是 163 这个 magic number，164就卡住了
增大 /dev/shm 至 512 M 还是不行啊?

**Comment by liuxiaotong15** [comment]
linux 上需要加上这句
if __name__ == "__main__":
    mp.set_start_method('forkserver')

**Comment by liuxiaotong15** [comment]
linux 上需要加上这句：
`if __name__ == "__main__": 
    mp.set_start_method('forkserver')`

**Comment by MorvanZhou** [comment]
应该是不同系统导致的多进程方法不一。参考@liuxiaotong15 的方式。

> linux 上需要加上这句：
> `if __name__ == "__main__": mp.set_start_method('forkserver')`
